// Scenario tests for mechanics. Load in the page console:
//   eval(await (await fetch('/dev/unittests.js')).text()); runTests()
window.runTests = function () {
  const out = {}; const T = (name, fn) => { try { const r = fn(); out[name] = r === true ? 'PASS' : 'FAIL ' + JSON.stringify(r); } catch (e) { out[name] = 'ERR ' + e.message; } };
  const steps = n => { for (let i = 0; i < n; i++) step(1 / 30); };
  const fresh = () => { UI.start(); G.res.wood = 9000; G.res.stone = 9000; G.res.gold = 9000; G.res.iron = 900; for (const u of G.units) if (u.side === 'enemy') killUnit(u, true); G.dayTimer = 9999; };
  const wallLine = () => { for (let x = 22; x <= 34; x++) placeBuilding('wall_wood', x, 22); };
  const enemy = (t, x, y) => { const u = spawnUnit(t, x, y); u.idle = false; u.wave = true; return u; };

  T('goon jumps wall', () => { fresh(); wallLine(); const g = enemy('goon', 28.5, 18.5); const before = G.buildings.filter(b => b.type === 'wall_wood').length; steps(30 * 12); const after = G.buildings.filter(b => b.type === 'wall_wood').length; return (g.y > 22.5 && after === before) || { y: g.y, before, after }; });
  T('activist chews wall instead', () => { fresh(); wallLine(); const a = enemy('activist', 28.5, 18.5); steps(30 * 10); const chewed = G.buildings.some(b => b.type === 'wall_wood' && b.hp < b.maxHp); return (a.y < 22 && chewed) || { y: a.y, chewed }; });
  T('nevertheless persists', () => { fresh(); const n = enemy('nevertheless', 40.5, 40.5); damageUnit(n, 1000); return (!n.dead && n.persistUsed && n.hp === n.def.hp2) || { dead: n.dead, hp: n.hp }; });
  T('tankie armor', () => { fresh(); const t = enemy('tankie', 40.5, 40.5); damageUnit(t, 8); return t.hp === t.maxHp - 2 || t.hp; });
  T('care bear heals tankie', () => { fresh(); const t = enemy('tankie', 45.5, 45.5); t.hp = 100; const c = enemy('carebear', 45.5, 46.5); steps(30 * 2); return t.hp > 110 || t.hp; });
  T('agitprop paints', () => { fresh(); const c = placeBuilding('cottage', 36, 30); const v = enemy('agitprop', 40.5, 31.5); v.target = c.id; v.fieldKey = 'e:b' + c.id; steps(30 * 6); return c.paint > 0 || { paint: c.paint, vx: v.x, vy: v.y }; });
  T('painted building takes 1.5x', () => { fresh(); const c = placeBuilding('cottage', 36, 30); c.paint = 30; damageBuilding(c, 10); return Math.abs(c.hp - (c.maxHp - 15)) < 0.01 || c.hp; });
  T('print shop scrubs paint', () => { fresh(); G.tech.done.add('gazette'); const c = placeBuilding('cottage', 36, 30); const p = placeBuilding('printshop', 38, 27); c.paint = 50; steps(30 * 9); return c.paint <= 0 || c.paint; });
  T('marksman prefers special', () => { fresh(); const m = spawnUnit('marksman', 40.5, 40.5); const a = enemy('activist', 42.5, 40.5); const mc = enemy('manchild', 44.5, 40.5); a.stun = 99; mc.stun = 99; steps(30 * 3); return (mc.hp < mc.maxHp && a.hp === a.maxHp) || { a: a.hp, mc: mc.hp }; });
  T('posse blocked by wall', () => { fresh(); for (let y = 38; y <= 42; y++) placeBuilding('wall_wood', 42, y); const p = spawnUnit('posse', 40.5, 40.5); const a = enemy('activist', 44.5, 40.5); a.stun = 99; steps(30 * 3); return a.hp === a.maxHp || a.hp; });
  T('posse hits in the open', () => { fresh(); const p = spawnUnit('posse', 40.5, 40.5); const a = enemy('activist', 42.5, 40.5), b = enemy('activist', 42.5, 41.5); a.stun = 99; b.stun = 99; steps(30 * 3); return (a.hp < a.maxHp && b.hp < b.maxHp) || { a: a.hp, b: b.hp }; });
  T('field piece splash', () => { fresh(); const f = spawnUnit('fieldpiece', 40.5, 40.5); const a = enemy('activist', 45.5, 40.5), b = enemy('activist', 45.5, 41.2); a.stun = 99; b.stun = 99; steps(30 * 5); return (a.dead && b.dead) || { a: a.hp, b: b.hp }; });
  T('field piece min range', () => { fresh(); const f = spawnUnit('fieldpiece', 40.5, 40.5); const a = enemy('activist', 41.5, 40.5); a.stun = 99; steps(30 * 5); return a.hp === a.maxHp || a.hp; });
  T('stakes bleed enemies', () => { fresh(); G.tech.done.add('stakes'); placeBuilding('stakes', 36, 30); const a = enemy('activist', 36.5, 30.5); a.stun = 99; steps(30 * 1); return a.hp < a.maxHp - 10 || a.hp; });
  T('deed office resists first flip', () => { fresh(); G.tech.done.add('deeds'); placeBuilding('deedoffice', 38, 27); const c = placeBuilding('cottage', 36, 30); slowTick(true); damageBuilding(c, 5000); const first = c.state; damageBuilding(c, 5000); return (first === 'player' && c.state === 'occupied') || { first, second: c.state }; });
  T('sernie drains + crate + retrieve', () => { fresh(); placeBuilding('cottage', 36, 30); const t0 = G.res.treasury; const s = enemy('sernie', 40.5, 31.5); s.hold = true; steps(30 * 26); const crate = G.buildings.find(b => b.state === 'crate'); if (!crate) return { treasury: G.res.treasury, stolen: s.stolen }; const drained = t0 - G.res.treasury; const g0 = G.res.gold; const m = spawnUnit('minuteman', crate.x + 1.5, crate.y + 0.5); steps(30 * 5); return (drained > 50 && crate.dead && G.res.gold >= g0 + 60) || { drained, dead: crate.dead, gold: G.res.gold - g0 }; });
  T('liz regulation', () => { fresh(); const l = enemy('liz', 42.5, 33.5); l.hold = true; steps(40); const c = placeBuilding('cottage', 36, 30); const reg = G.regulation && c.hp === Math.round(c.maxHp * 0.5) && c.recover > 0; const cost1 = repairCost(c); killUnit(l); slowTick(true); const cost2 = repairCost(c); return (reg && !G.regulation && cost1.gold === cost2.gold * 3) || { reg, hp: c.hp, cost1, cost2, regNow: G.regulation }; });
  T('alex shuts industry + seizure retargets', () => { fresh(); const m = placeBuilding('mill', 36, 30); const a = enemy('alex', 42.5, 33.5); a.hold = true; const sz = enemy('seizure', 46.5, 33.5); steps(30 * 9); return (m.shut > 0 && sz.target === m.id) || { shut: m.shut, tgt: sz.target, mill: m.id }; });
  T('seizure channel flips', () => { fresh(); const m = placeBuilding('mill', 36, 30); const sz = enemy('seizure', 38.5, 30.5); steps(30 * 12); return m.state === 'occupied' || { state: m.state, ch: sz.channel, x: sz.x, y: sz.y }; });
  T('tech research + unlock + train', () => { fresh(); G.tech.done.clear(); const c0 = canTrain('marksman').ok; startResearch('stakes'); steps(30 * 21); startResearch('marksmen'); steps(30 * 31); const ok = G.tech.done.has('marksmen'); trainUnit('marksman'); steps(30 * 13); const n = G.units.filter(u => !u.dead && u.type === 'marksman').length; return (!c0 && ok && n === 1) || { c0, ok, n, cur: G.tech.current }; });
  T('lodge halves muster delay', () => { fresh(); G.tech.done.add('lodge'); placeBuilding('militiahall', 36, 30); const d0 = musterDelay(); placeBuilding('lodge', 38, 27); slowTick(true); const d1 = musterDelay(); return Math.abs(d1 - d0 / 2) < 0.01 || { d0, d1 }; });
  T('warehouse +20%', () => { fresh(); G.tech.done.add('storage'); const f = placeBuilding('farm', 36, 29); const before = G.res.food; steps(30); const gain1 = G.res.food - before; placeBuilding('warehouse', 39, 27); slowTick(true); const b2 = G.res.food; steps(30); const gain2 = G.res.food - b2; return Math.abs((gain2 - gain1) - 12 * 0.2 / DAY_LENGTH) < 0.005 || { gain1, gain2 }; });
  T('organizer prefers school', () => { fresh(); G.tech.done.add('school'); placeBuilding('cottage', 36, 33); const s = placeBuilding('school', 36, 30); const o = enemy('organizer', 44.5, 31.5); steps(2); return o.target === s.id || { tgt: o.target, school: s.id }; });
  T('megaphone deafens', () => { fresh(); const m = spawnUnit('militia', 40.5, 40.5); const n = enemy('nevertheless', 42.5, 40.5); n.stun = 0; n.megaT = 0.1; steps(30 * 1); return m.deaf > 0 || m.deaf; });
  T('goon pack spawns together', () => { fresh(); G.momentum = 0; spawnWave(9); const packs = G.wave.list.filter(e => e.type === 'goon'); return (packs.reduce((a, e) => a + e.n, 0) === 4 && packs.every(e => e.n <= 3)) || packs; });
  T('lieutenant enters with wave', () => { fresh(); G.momentum = 0; spawnWave(10); steps(30 * 12); return G.units.some(u => !u.dead && u.type === 'sernie') || G.wave; });
  T('win on final day', () => { fresh(); G.dayTimer = 0.01; while (G.day < WIN_DAY) { G.dayTimer = 0.01; step(1 / 30); } steps(30 * 14); for (const u of G.units) if (!u.dead && u.side === 'enemy') killUnit(u, true); steps(3); return (G.over && G.won) || { over: G.over, won: G.won, day: G.day }; });

  T('encampments exist + print shop reveals', () => { fresh(); const camps = G.buildings.filter(b => b.state === 'enemy'); G.tech.done.add('gazette'); placeBuilding('printshop', 38, 27); updateVision(); const seen = camps.every(b => G.vis[tileIndex(b.x, b.y)] >= 1); return (camps.length === ENCAMPMENTS.length && seen) || { n: camps.length, seen }; });
  T('raid encampment: loot + backlash', () => { fresh(); const camp = G.buildings.find(b => b.state === 'enemy'); const g0 = G.res.gold; const m = spawnUnit('marksman', camp.x + 4.5, camp.y + 1.5); cmdAttackBuilding([m], camp); for (let i = 0; i < 30 * 70 && !camp.dead; i++) step(1 / 30); const angry = G.units.filter(u => !u.dead && u.side === 'enemy' && !u.idle && Math.hypot(u.x - camp.x - 1.5, u.y - camp.y - 1.5) < 6).length; return (camp.dead && G.res.gold >= g0 + 90 && angry >= 8) || { dead: camp.dead, gold: G.res.gold - g0, angry }; });
  T('noise wakes idle', () => { fresh(); const a = enemy('activist', 40.5, 30.5); a.idle = true; a.wave = false; const m = spawnUnit('militia', 36.5, 30.5); steps(30 * 2); return !a.idle || { idle: a.idle }; });
  T('minuteman is quiet', () => { fresh(); const a = enemy('activist', 42.5, 30.5); a.idle = true; a.wave = false; const m = spawnUnit('minuteman', 37.5, 30.5); m.cool = 99; steps(30 * 2); return a.idle === true || { idle: a.idle }; });
  T('occupation skin', () => { fresh(); const c = placeBuilding('cottage', 36, 30); damageBuilding(c, 9999); return (c.state === 'occupied' && OCC_SKINS.cottage.includes(c.skin)) || c.skin; });
  T('war communism revives', () => { fresh(); const w = enemy('warcommunism', 40.5, 30.5); w.hold = true; const a = enemy('activist', 42.5, 30.5); a.stun = 99; const n0 = G.units.filter(u => !u.dead && u.type === 'activist').length; damageUnit(a, 999); steps(30 * 7); const n1 = G.units.filter(u => !u.dead && u.type === 'activist').length; return (n1 === n0 && G.units.some(u => !u.dead && u.revived)) || { n0, n1 }; });
  T('gosplan siphons + tankie', () => { fresh(); const g = enemy('gosplan', 42.5, 33.5); g.hold = true; slowTick(true); const gold0 = G.res.gold; G.publicFund = 0; steps(30 * 10); const fund = G.publicFund; G.publicFund = 100; steps(2); return (fund > 0.5 && G.units.some(u => !u.dead && u.type === 'tankie')) || { fund, tankie: G.units.filter(u => u.type === 'tankie').length }; });
  T('listening session freezes commands', () => { fresh(); const l = enemy('listening', 42.5, 33.5); l.hold = true; l.ltT = 24; steps(30 * 2); const warned = G.freeze.warn > 0; steps(30 * 5); const on = G.freeze.t > 0; const m = spawnUnit('militia', 36.5, 30.5); cmdMove([m], 34, 30); const blocked = m.state === 'idle' && !canPlace('wall_wood', 34, 30).ok; steps(30 * 10); const off = G.freeze.t <= 0; return (warned && on && blocked && off) || { warned, on, blocked, off, t: G.freeze.t }; });
  T('committee: aura, momentum lock, resolution, touch loses', () => { fresh(); G.momentum = 10; const c = enemy('committee', 40.5, 32.5); c.hold = true; G.committee = c; slowTick(true); steps(2); const cot = placeBuilding('cottage', 36, 30); slowTick(true); const aura = cot.inCommittee; const mom = G.momentum >= 80; const rc = repairCost(G.hall); c.hp = c.maxHp * 0.7; steps(2); const res = c.quarters === 2; c.hold = false; c.x = G.hall.x + 1.5; c.y = G.hall.y + 3.6; steps(2); return (aura && mom && res && G.over && !G.won) || { aura, mom, res, over: G.over, won: G.won, q: c.quarters }; });
  T('committee death wins', () => { fresh(); const c = enemy('committee', 44.5, 44.5); G.committee = c; damageUnit(c, 99999); return (G.over && G.won) || { over: G.over, won: G.won }; });
  T('day 20 wave has boss + lieutenant', () => { fresh(); G.momentum = 0; spawnWave(20); steps(30 * 14); const boss = G.units.some(u => !u.dead && u.type === 'committee'); const lt = G.units.some(u => !u.dead && u.def.lt && !u.def.boss); return (boss && lt) || { boss, lt }; });

  T('procedural maps valid (10 seeds)', () => { const bad = []; for (let sd = 1; sd <= 10; sd++) { const m = generateMap(sd * 7919); const reach = terrainReach(m.terrain); const clear = [26, 27, 28].every(x => [26, 27, 28].every(y => m.terrain[tileIndex(x, y)] === TER.GRASS)); const stone = m.terrain.some(v => v === TER.STONE), iron = m.terrain.some(v => v === TER.IRON); if (!(m.camps.length === 5 && reach >= 0.75 && clear && stone && iron)) bad.push({ sd, camps: m.camps.length, reach: +reach.toFixed(2), clear, stone, iron }); } return bad.length === 0 || bad; });
  T('procedural game starts + wave arrives', () => { UI.start(); newGame({ seed: 4242, difficulty: 'hard' }); G.dayTimer = 0.01; steps(30 * 20); const wave = G.wave && G.wave.total; return (G.seed === 4242 && G.difficulty === 'hard' && wave >= 20 && G.buildings.filter(b => b.state === 'enemy').length === 5) || { seed: G.seed, wave, camps: G.buildings.filter(b => b.state === 'enemy').length }; });
  T('difficulty scales waves + start', () => { newGame({ seed: 0, difficulty: 'easy' }); const g = G.res.gold; G.momentum = 0; spawnWave(2); const easy = G.wave.total; newGame({ seed: 0, difficulty: 'hard' }); G.momentum = 0; spawnWave(2); const hard = G.wave.total; return (easy < hard && g === Math.round(START_RES.gold * 1.4)) || { easy, hard, g }; });
  T('homesteaders spawn per cottage + flee', () => { fresh(); placeBuilding('cottage', 36, 30); slowTick(true); const h = G.units.find(u => !u.dead && u.type === 'homesteader'); if (!h) return 'none'; const a = enemy('activist', h.x + 2, h.y); a.stun = 99; steps(30 * 2); return (h.flee > 0) || { flee: h.flee }; });
  T('homesteader gets organized', () => { fresh(); for (const m of G.units.filter(u => u.type === 'minuteman')) killUnit(m, true); placeBuilding('cottage', 36, 30); slowTick(true); const h = G.units.find(u => !u.dead && u.type === 'homesteader'); const cap0 = G.hh.cap; const a = enemy('activist', h.x, h.y); steps(30 * 2); const org = G.organized === 1 && h.dead && G.hh.cap === cap0 - 1; for (const conv of G.units.filter(u => !u.dead && u.organized)) killUnit(conv); return (org && G.organized === 0 && G.hh.cap === cap0) || { org, organized: G.organized, cap: G.hh.cap, cap0, hdead: h.dead }; });
  T('save / load roundtrip', () => { fresh(); placeBuilding('cottage', 36, 30); placeBuilding('tower', 34, 28); G.tech.done.add('stakes'); G.res.gold = 1234; G.day = 5; const nb = G.buildings.length; const nu = G.units.filter(u => !u.dead).length; const ok1 = saveGame(); const ok2 = loadGame(); const same = G.buildings.length === nb && G.units.filter(u => !u.dead).length === nu && G.res.gold === 1234 && G.day === 5 && G.tech.done.has('stakes') && G.hall && G.hall.type === 'townhall'; steps(30 * 3); return (ok1 && ok2 && same && !G.over) || { ok1, ok2, nb, nb2: G.buildings.length, nu, nu2: G.units.filter(u => !u.dead).length, gold: G.res.gold, day: G.day }; });
  return out;
};
